---
- name: Build Docker Image
  hosts: localhost
  gather_facts: no

  tasks:
  - name: Build Docker image
    docker_image:
      name: act11img
      path: ~/Cuyugan_Activity11
      state: present

